### ISSUE TITLE
Webpack2 compatibility

### ISSUE THREAD

**Issue by DanielKucal** [BinaryMuse/toml-node#32]
Hello, when I was trying to use this repository with Webpack v2.2.0-rc.4 I got an error:

> some\path\node_modules\loader-runner\lib\loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
         ^
Error: Module 'some\path\node_modules\toml\index.js' is not a loader (must have normal or pitch function)
    at loadLoader (some\path\node_modules\loader-runner\lib\loadLoader.js:35:10)
    at iteratePitchingLoaders (some\path\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at runLoaders (some\path\node_modules\loader-runner\lib\LoaderRunner.js:357:2)
    at NormalModule.doBuild (some\path\node_modules\webpack\lib\NormalModule.js:129:2)
    at NormalModule.build (some\path\node_modules\webpack\lib\NormalModule.js:180:15)
    at Compilation.buildModule (some\path\node_modules\webpack\lib\Compilation.js:127:10)
    at factoryCallback (some\path\node_modules\webpack\lib\Compilation.js:304:11)
    at some\path\node_modules\webpack\lib\NormalModuleFactory.js:242:4
    at some\path\node_modules\webpack\lib\NormalModuleFactory.js:93:13
    at some\path\node_modules\tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\CompatibilityPlugin.js:51:4)
    at some\path\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at some\path\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at some\path\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at some\path\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at some\path\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (some\path\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (some\path\node_modules\tapable\lib\Tapable.js:208:13)
    at onDoneResolving (some\path\node_modules\webpack\lib\NormalModuleFactory.js:68:11)
    at onDoneResolving (some\path\node_modules\webpack\lib\NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I think it expects exported function to be like:

	var parser = require('./lib/parser');
	var compiler = require('./lib/compiler');

	module.exports = function(input) {
		var nodes = parser.parse(input.toString());
		return compiler.compile(nodes);
	};

Could someone solve it, please?

**Comment by BinaryMuse** [comment]
Hm, can you share a bit more information? How exactly are you using this with webpack? Do you have a project I can use to reproduce your issue? The stack trace seems to indicate webpack is trying to use this project as a loader, but it is not a webpack loader.

**Comment by DanielKucal** [comment]
Unfortunately I don't have such project for this moment. I use the [toml-loader](https://github.com/KyleAMathews/toml-loader) which uses this library.

**Comment by BinaryMuse** [comment]
Ah, I see what's happening here. In webpack v1, you could leave off the "-loader" stuffix in your config. For example to use `babel-loader` you could just say `babel`. In v2, this is no longer true — you must put the whole thing.

So, it's likely that you listed `toml`, which is trying to load this library, not the loader. Change it to `toml-loader`.

**Comment by DanielKucal** [comment]
Oh, wow. I actually had some lines of `require('toml!../../assets/i18n/en.toml');` and changing it to `require('toml-loader!../../assets/i18n/en.toml');` fixed the problem! 
You are a genius, thanks so much for your time and priceless help :)
